---
title: "Introducción a Quarto"
subtitle: "Crea hermosos y útiles articulos, paginas web, documentos, presentaciones, dashboards, entre otros"
author: 
    - name: "Andres Humberto Chirinos Lizondo"
      affiliation: 
        - "Carrera de Estadística - UMSA"
        - "Sociedad Científica de Estudiantes de Estadística"
      email: ahchirinos@umsa.bo
      orcid: 0009-0004-1628-6135
      corresponding: true
      url: https://www.linkedin.com/in/andres-chirinos

date: 2024-10-31
lang: es
format:
    revealjs: 
        theme: dark
        slide-number: true
        incremental: true   
        scrollable: true
        multiplex: true
        chalkboard:
            buttons: true
        preview-links: auto
        logo: images/quarto.png
        footer: Más información <https://quarto.org> | [Repositorio en GitHub](https://github.com/andres-chirinos/charla-31-quarto)
---

# ¿Qué es Quarto?

- Quarto es una plataforma de publicación **científica** y **técnica**.
- Permite crear documentos **reproducibles** y **dinámicos**.
- Soporta **múltiples formatos** de salida como HTML, PDF, Word, y presentaciones.

## Como plataforma de publicación

Nos provee de herramientas que nos ayudan al proceso de publicación, al estar orientada al área científica y técnica nos da la facilidad de usar tecnologias del entorno como ser

### Latex
$$
\int_{a}^{b} \frac{1}{b-a}
$$

### Python
```python
print("hello world")
```

### R
```r
print("hello world")
```

### Diagramas
```{mermaid}
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
``` 

## Como método de dinamismo y replicabilidad

Este nos ayuda a gestionar todo el proyecto en una misma ubicación y archivos, evitando la duplicidad y también haciendo más sencillo su replicabilidad completa.

- **Manuscrito**: El documento principal que contiene el texto del artículo.
- **Tablas**: Datos tabulados que complementan el manuscrito.
- **Figuras**: Gráficos, diagramas y fotografías que ilustran los resultados.
- **Datos Suplementarios**: Información adicional que respalda los hallazgos del estudio.
- **Código Fuente**: Scripts y programas utilizados para el análisis de datos.
- **Referencias**: Lista de trabajos citados en el manuscrito.

## Como proveedor de formatos
Ya que todo nuestro proyecto esta estandarizado y este cuenta con toda la información utilizada, este motor nos puede ayudar a exportar nuestro proyecto al formato que deseamos, incluso customizables (formatos para revistas, etc).

- PDF (Estandar o incluso el formato de Journey Asociation Statistics of America JASA)
  - APA 7
  - Hardvard
- Word
- HTML
- Markdown
- Latex (Typst)
- Entre otros

# ¿Qué se puede hacer con Quarto?

- Crear [informes]() técnicos y científicos.
- Generar [documentos](https://sociest.org/ue-report/index.pdf) reproducibles con código embebido.
- Desarrollar [presentaciones]() interactivas.
- Publicar [libros]() y sitios web.
- Entre otros

[Galleria de Quarto](https://quarto.org/docs/gallery/)

# ¿Por qué nos sirve Quarto?

- Facilita la integración de texto, código y resultados.
- Promueve la reproducibilidad y transparencia en la investigación.
- Soporta múltiples lenguajes de programación como R, Python y Julia.
- Permite la colaboración y el versionado de documentos atraves de git (github, gitlab, etc),etc.

# Vamos unos ejemplos 

- [Analisis de unidades educativas en bolivia](https://sociest.org/ue-report/)
- [Dashboard USDT/BOB](https://andres-chirinos.github.io/usdt-bob-dashboard/)
- [Pagina Web SOCIEST](https://sociest.org)
- [Esta Presentación]()

# Hagamos un ejercicio

Creemos un manuscrito

1. [Instalemos Quarto](https://quarto.org/docs/get-started/)

2. Empecemos un proyecto

# Muchas Gracias